packageExtensions:
  eslint-module-utils@*:
    peerDependencies:
      eslint: "*"
  eslint-plugin-prettier@*:
    peerDependencies:
      eslint-config-prettier: "*"
  jquery-deparam@*:
    peerDependencies:
      jquery: "*"
  promise-inflight@*:
    peerDependencies:
      bluebird: "*"
  stylelint-prettier@*:
    peerDependencies:
      stylelint-config-prettier: "*"
  webpack@*:
    peerDependencies:
      webpack-cli: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.1.1.cjs
