version: 2.1

jobs:
  build:
    working_directory: ~/herman
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - herman-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      # - run:
      #     name: Compile Assets
      #     command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - ./node_modules
      - save_cache:
          key: herman-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  lint:
    working_directory: ~/herman
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint:ci

  test:
    working_directory: ~/herman
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test Sass
          command: yarn test:sass
      - run:
          name: Test JS
          command: yarn test:js:src:ci
          environment:
            MOCHA_FILE: './coverage/src/junit.xml'
      - run:
          name: Test Client JS
          command: yarn test:js:client:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: './coverage/client'
      - store_artifacts:
          path: coverage
          destination: js-test-reports
      - persist_to_workspace:
          root: .
          paths:
            - coverage

  check-test-coverage:
    working_directory: ~/herman
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Check Test Coverage
          command: |
            yarn nyc check-coverage --temp-dir coverage/src
            yarn nyc check-coverage --temp-dir coverage/client
      - run:
          name: Report Test Coverage
          command: |
            yarn nyc report --reporter=text-lcov --temp-dir coverage/src | yarn coveralls
            yarn nyc report --reporter=text-lcov --temp-dir coverage/client | yarn coveralls
            curl -k "https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN}" -d "payload[build_num]=${CIRCLE_BUILD_NUM}&payload[status]=done"
          environment:
            COVERALLS_PARALLEL: 'true'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - check-test-coverage:
          requires:
            - test
