version: 2.1

jobs:
  build:
    working_directory: ~/herman
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - herman-yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - persist_to_workspace:
          root: .
          paths:
            - ./node_modules
      - save_cache:
          key: herman-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  build-node-6:
    working_directory: ~/herman
    docker:
      - image: node:6
    steps:
      - checkout
      - restore_cache:
          keys:
            - herman-node6-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --ignore-engines
      - save_cache:
          key: herman-node6-modules-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  lint:
    working_directory: ~/herman
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint JS
          command: yarn gulp eslint
      # - run:
      #     name: Lint Sass
      #     command: yarn gulp sasslint

  test-sass:
    working_directory: ~/herman
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test Sass
          command: yarn gulp sasstest

  test-js:
    working_directory: ~/herman
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run JS Tests
          command: yarn gulp jstest
      - run:
          name: Run Client JS Tests
          command: yarn gulp clienttest
      - run:
          name: Report Test Coverage
          command: |
            yarn nyc report --reporter=text-lcov | yarn coveralls
            yarn nyc report --reporter=text-lcov --temp-directory ./jscov/client/ | yarn coveralls
            curl -k "https://coveralls.io/webhook?repo_token=${COVERALLS_REPO_TOKEN}" -d "payload[build_num]=${CIRCLE_BUILD_NUM}&payload[status]=done"
          environment:
            COVERALLS_PARALLEL: 'true'
      - run:
          name: Check Test Coverage
          command: |
            yarn nyc check-coverage
            yarn nyc check-coverage --temp-directory ./jscov/client/
      - store_artifacts:
          path: jscov
          destination: js-reports
      - store_test_results:
          path: jscov

  test-node-6:
    working_directory: ~/herman
    docker:
      - image: node:6
    steps:
      - checkout
      - restore_cache:
          keys:
            - herman-node6-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Run JS Tests [node 6]
          command: yarn gulp jstest-node6
      - store_artifacts:
          path: jscov
          destination: js-reports
      - store_test_results:
          path: jscov

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - build-node-6
      - lint:
          requires:
            - build
      - test-sass:
          requires:
            - build
      - test-js:
          requires:
            - build
      - test-node-6:
          requires:
            - build-node-6
